import "./globals.css";
import Providers from "./components/Providers/Providers";
import UploadForm from "./components/Upload/UploadForm";
import LoginModal from "./components/Modals/LoginModal";
import NewProjectModal from "./components/Modals/NewProjectModal";

import { Roboto } from "next/font/google";

const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400", "500", "700"] });

export const metadata = {
  title: "Lama",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          <LoginModal />
          <NewProjectModal />
          <UploadForm />
          {children}
        </Providers>
      </body>
    </html>
  );
}
